//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudForm.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tabla
    {
        public int id { get; set; }
        public byte[] nombre { get; set; }
        public byte[] correo { get; set; }
        public Nullable<System.DateTime> fechanacimiento { get; set; }
        public string nombre1 { get; set; }
        public string correo1 { get; set; }
    }
}
